<h1>Step 2</h1>
<p>Details!</p>
<br>
<p>Your dashboard is located <a href="/dashboard">here</a>. It is where you can add, modify, and delete various things from your site.</p>
<p>You should currently be logged in (check by looking at the top right corner)</p>
<p>Places to begin:</p>
<ul>
    <li>Modify the navbar (located in the header.phtml file, editable from the dashboard)</li>
    <li>Create your first page</li>
    <li>Delete everything and make your own stuff from the same codebase</li>
</ul>
<p>Please press the button to finish up the setup</p>
<a class="btn btn-success" href="/setup-site?step=3">Finish this thing up!</a>
