<?php
try { include '../config.php'; } catch (Exception $e) { include '../ex-config.php'; }

$conn = new mysqli($sqlserver,$sqluser,$sqlpass,$sqldb);

if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

$sql = "SELECT * FROM `afroraydude-site`.`blog` ORDER BY `id` DESC";

$result = $conn->query($sql) or die($conn->error);

$page_title = "Blogo";
// end header processing
include_once 'header.phtml';
$result = $conn->query($sql) or die($conn->error);
if ($result->num_rows !== 0) : ?>
    <div class="col-xs-12 col-md-8">
    <?php while ($row = $result->fetch_assoc()) :
        $entry = strtotime($row['created_timestamp']); ?>

            <h1><?=  $row['title'] ?></h1>
            <small><?= date('M d, y H:i', $entry) ?></small>
            <hr>
            <div class="blog-content">
                <?= $row['content'] ?>
            </div>

    <?php endwhile; ?>
    </div>
<?php endif; ?>
<div class="hidden-xs hidden-sm col-md-4 blog-padding hidden-XSplit hidden-sm">
    <div class="well">
        <div class="panel-body">
            <h2>About my blog</h2>
            <p>This is just something that I added because I was bored. If I post it will probably be short because nobody goes onto this site</p>
        </div>
    </div>
</div>
<?php
include_once 'footer.phtml';
$conn->close();
?>
