<?php
require '../config.php';

$conn = new PDO("mysql:host=$sqlserver;dbname=$sqldb", $sqluser, $sqlpass);

if (isset($name)) {
    $page_name = htmlspecialchars($name);
    //$page_name = mysqli_real_escape_string($conn, $page_name);
    
} else {
    $page_name = "index";
}

$return = 'Something something something error';
/**
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}
*/
$sql = "SELECT * FROM `afroraydude-site`.`pages` WHERE `name` LIKE '{$page_name}'";

$stmt = $conn->query($sql);

if (0 !== $stmt->rowCount())  :
  while($row =$stmt->fetch(PDO::FETCH_ASSOC)) {
    $page_title = $row['page-title'];
    $text = $row['content'];
  } ?>
<?php else :
    $page_title = "404 Page Not Found";
endif;
// end header processing
include_once 'header.phtml';

if (!empty($text)) :
  echo $text;
else : ?>
            <h1>Page Not Found</h1>
            <p>The page you are looking for could not be found. Check the address barto ensure your URL is spelled correctly.
                If all else fails, you can visit our home page at the link below.</p>
            <a href='<?=  '../../../../'  // 'http://afroraydude.com ' ; ?>'>Visit the Home Page</a>
            <?php endif;
include_once 'footer.phtml';
//$conn->close();
?>