<?php
try { include_once '../config.php'; } catch (Exception $e) { include '../ex-config.php'; }

$conn = new mysqli($sqlserver,$sqluser,$sqlpass,$sqldb);

if (isset($name)) {
    $page_name = htmlspecialchars($name);
    $page_name = mysqli_real_escape_string($conn, $page_name);
    
} else {
    $page_name = "index";
}

$return = 'Something something something error';

if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

$sql = "SELECT * FROM `afroraydude-site`.`pages` WHERE `name` LIKE '{$page_name}'";

$result = $conn->query($sql) or die($conn->error);

if ($result->num_rows !== 0) : ?>
    <?php
    while($row = $result->fetch_assoc()) {
        $page_title = $row['page-title'];

    } ?>
        <?php else :
    $page_title = "404 Page Not Found";

endif; ?>

<?php // end header processing ?>

<?php
include_once 'header.phtml';
$result = $conn->query($sql) or die($conn->error);
if ($result->num_rows !== 0) :
while($row = $result->fetch_assoc()) {
$lm_notif = "Page was last modified on ".$row['last-modified'];

echo $row['content'];
}
else : ?>
            <h1>Page Not Found</h1>
            <p>The page you are looking for could not be found. Check the address barto ensure your URL is spelled correctly.
                If all else fails, you can visit our home page at the link below.</p>
            <a href='<?=  '../../../../'  // 'http://afroraydude.com ' ; ?>'>Visit the Home Page</a>
            <?php endif;
include_once 'footer.phtml';
$conn->close();
?>