<?php
include_once "../config.php";
$page_title = "Create Page";
include_once 'header.phtml';
if (!isset($_SESSION['username'])) :?>
    <html><head><meta http-equiv="refresh" content="0; url=/"></head><body></body></html>
<?php else :
?>

    <form class="form" action = "<?php echo htmlspecialchars('/writepage'); ?>" method = "post">
        <div class="form-group ">
            <label class="control-label requiredField" for="name">
                Page Name
                <span class="asteriskField">
        *
       </span>
            </label>
            <input class="form-control" id="name" name="name" type="text"/>
        </div>
        <div class="form-group ">
            <label class="control-label requiredField" for="url">
                Page URL
                <span class="asteriskField">
        *
       </span>
            </label>
            <?php if (isset($_GET['url'])) : ?>
                <input class="form-control" id="url" name="url" readonly value="<?=$_GET['url']?>" type="text"/>
            <?php else: ?>
                <input class="form-control" id="url" name="url" type="text"/>
            <?php endif; ?>
        </div>
        <div class="form-group ">
            <label class="control-label requiredField" for="content">
                Page Content
                <span class="asteriskField">
        *
       </span>
            </label>
            <textarea class="form-control editor" cols="40" id="content" name="content" rows="10"></textarea>
        </div>
        <div class="form-group">
            <div>
                <button class="btn btn-primary " name="submit" type="submit">
                    Submit
                </button>
            </div>
        </div>
    </form>
<?php include_once 'footer.phtml'; endif; ?>