<?php
include_once "../config.php";
$page_title = "Create User";
include_once 'header.phtml';
if (!isset($_SESSION['username']) || $_SESSION['role'] != 1) :?>
    <html>
    <head>
        <meta http-equiv="refresh" content="0; url=/">
    </head>
    <body></body>
    </html>
<?php else :
    ?>
    <?php
    if (empty($messages) == false) :
        $error = $messages['Error'];
        ?>
        <div class="alert alert-danger alert-dismissable"><p><?= $error[0] ?></p></div>
    <?php endif; ?>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/zxcvbn/4.2.0/zxcvbn.js"></script>

    <form class="form" action="<?php echo htmlspecialchars('/createuser'); ?>" method="post">
        <div class="col-md-4">
            <div class="form-group ">
                <label class="control-label requiredField" for="username">
                    Username
                    <span class="asteriskField">
        *
       </span>
                </label>

                <input class="form-control" id="name" name="username" type="text"/>
            </div>

            <div class="form-group ">
                <label class="control-label requiredField" for="name">
                    Password
                    <span class="asteriskField">
        *
       </span>
                </label>
                <input class="form-control" id="password" name="password" type="password"/>
                <meter max="4" id="password-strength-meter" width="100%" size="100"></meter>
                <p id="password-strength-text"></p>
            </div>

            <div class="form-group">
                <label class="control-label requiredField" for="userrole">
                    User Role
                    <span class="asteriskField">
        *
       </span>
                    <select id="userrole" name="userrole" class="form-control">
                        <option value="1">Admin</option>
                        <option value="2">Manager</option>
                        <option value="3">Poster</option>
                        <option value="4">User</option>
                    </select>
            </div>

            <div class="form-group">
                <div>
                    <button class="btn btn-primary " name="submit" type="submit">
                        Submit
                    </button>
                </div>
            </div>
        </div>
        <script>
            var strength = {
                0: "Worst",
                1: "Bad",
                2: "Weak",
                3: "Good",
                4: "Strong"
            };
            var password = document.getElementById('password');
            var meter = document.getElementById('password-strength-meter');
            var text = document.getElementById('password-strength-text');

            password.addEventListener('input', function() {
                var val = password.value;
                var result = zxcvbn(val);

                // Update the password strength meter
                meter.value = result.score;

                // Update the text indicator
                if (val !== "") {
                    text.innerHTML = "Strength: " + strength[result.score];
                } else {
                    text.innerHTML = "";
                }
            });
        </script>
    </form>
    <?php include_once 'footer.phtml'; endif; ?>