<?php
include_once "../config.php";

if (!isset($_SESSION['username']) || $_SESSION['role'] == 3) :?>
    <html>
    <head>
        <meta http-equiv="refresh" content="0; url=/">
    </head>
    <body></body>
    </html>
<?php else :

    $conn = new mysqli($sqlserver, $sqluser, $sqlpass, $sqldb);

    $sql = "SELECT * FROM `afroraydude-site`.`pages`";
    $sql2 = "SELECT * FROM `afroraydude-site`.`blog`";
    $sql3 = "SELECT * FROM `afroraydude-site`.`files`";
    $sql4 = "SELECT * FROM `afroraydude-site`.`users`";

    $result = $conn->query($sql) or die($conn->error);

    $page_title = "Dashboard";
    include_once "header.phtml";

// PROGRESS BARS http://progressbarjs.readthedocs.io/en/latest/api/shape/
    ?>
    <script>
        // when DOM is ready
        $(document).ready(function () {

            // Attach Button click event listener
            $("#myBtn").click(function () {

                // show Modal
                $('#myModal').modal('show');
            });
        });

    </script>
    <div class="col-xs-12 col-sm-6">
        <h1>Dashboard</h1>
    </div>
    <div class="hidden-xs col-xs-12 col-sm-6 btn-group right-buttons">
        <a href="/upload" class="btn btn-primary btn-sm">+ File</a>
        <a class="btn btn-primary btn-sm" href="/dashboard/createpost">+ Post</a>
        <?php if ($_SESSION['role'] == 1): ?>
            <a href="/dashboard/createpage" class="btn btn-primary btn-sm">+ Page</a>
            <a class="btn btn-primary btn-sm" href="/dashboard/editcss">Edit CSS</a>
        <?php endif; ?>
    </div>
    <div clas="col-xs-12">
        <?php
        if (empty($messages) == false) :
            $error = $messages['Error'];
            ?>
            <div class="alert alert-danger alert-dismissable"><p><?= $error[0] ?></p></div>
        <?php endif; ?>
    </div>
    <?php if ($_SESSION['role'] == 1):
    if ($result->num_rows !== 0) : ?>
        <div class="col-xs-12">
            <h2>Page Management</h2>
            <table class="table table-bordered table-hover table-responsive">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Title</th>
                    <th>Last modified</th>
                    <th>Options</th>
                </tr>
                </thead>
                <tbody>
                <?php while ($row = $result->fetch_assoc()) : ?>
                    <tr>
                        <td><?= $row['id'] ?></td>
                        <td><?= $row['name'] ?></td>
                        <td><?= $row['page-title'] ?></td>
                        <td><?= $row['last-modified'] ?></td>
                        <td><a href="/dashboard/editpage?page=<?= $row['id'] ?>">Edit Page</a> <a
                                    href="/delpage?page=<?= $row['id'] ?>">Delete Page</a></td>
                    </tr>
                <?php endwhile; ?>
                </tbody>
            </table>
        </div>
    <?php endif;
    $result = $conn->query($sql4) or die($conn->error);
    if ($result->num_rows !== 0) :?>
        <div class="col-xs-12">
            <h2>User Management</h2>
            <table class="table table-bordered table-hover table-responsive">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Username</th>
                    <th>Join Timestamp</th>
                    <th>Last Logged In</th>
                    <th>Options</th>
                </tr>
                </thead>
                <tbody>
                <?php while ($row = $result->fetch_assoc()) : ?>
                    <tr>
                        <td><?= $row['id'] ?></td>
                        <td><?= $row['username'] ?></td>
                        <td><?= $row['joined_timestamp'] ?></td>
                        <td><?= $row['last_login_timestamp'] ?></td>
                        <td><a href="/dashboard/edituser?user=<?= $row['id'] ?>">Edit User</a> <a
                                    href="/deluser?user=<?= $row['id'] ?>">Delete User</a></td>
                    </tr>
                <?php endwhile; ?>
                </tbody>
            </table>
        </div>
    <?php endif; endif; ?>

    <?php
    $result = $conn->query($sql2) or die($conn->error);
    if ($result->num_rows !== 0) : ?>

        <div class="col-xs-12">

            <h2>Post Management</h2>
            <table class="table table-bordered table-hover table-responsive">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Post Timestamp</th>
                    <th>Options</th>
                </tr>
                </thead>
                <tbody>
                <?php while ($row = $result->fetch_assoc()) : ?>
                    <tr>
                        <td><?= $row['id'] ?></td>
                        <td><?= $row['title'] ?></td>
                        <td><?= $row['created_timestamp'] ?></td>
                        <td><a href="/dashboard/editpost?post=<?= $row['id'] ?>">Edit Post</a> <a
                                    href="/delpost?post=<?= $row['id'] ?>">Delete Post</a></td>
                    </tr>
                <?php endwhile; ?>
                </tbody>
            </table>
        </div>
    <?php endif;
    $result = $conn->query($sql3) or die($conn->error);
    if ($result->num_rows !== 0) : ?>
        <div class="col-xs-12">
            <h2>File Management</h2>
            <table class="table table-bordered table-hover table-responsive">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>File Name</th>
                    <th>File URL</th>
                    <th>Upload Date</th>
                    <th>Options</th>
                </tr>
                </thead>
                <tbody>
                <?php while ($row = $result->fetch_assoc()) : ?>
                    <tr>
                        <td><?= $row['id'] ?></td>
                        <td><?= $row['filename'] ?></td>
                        <td>/uploads/<?= $row['fullurl'] ?></td>
                        <td><?= $row['upload_timestamp'] ?></td>
                        <td><a href="/uploads/<?= $row['fullurl'] ?>">Go to file</a> <a
                                    href="/delfile?file=<?= $row['fullurl'] ?>">Delete file</a></td>
                    </tr>
                <?php endwhile; ?>
                </tbody>
            </table>

        </div>
    <?php endif; ?>
    <div class="col-xs-12">
        <h2>Template Management</h2>
        <?php
        $templatelist = scandir('../templates');
        foreach ($templatelist as $templateitem):
            if ($templateitem !== '.' && $templateitem !== '..' && strpos($templateitem, 'phtml') == true): ?>
                <a href="/dashboard/edittemplate?template=<?= $templateitem ?>"><?= $templateitem ?></a><br>
            <?php endif; endforeach; ?>
    </div>
    <?php include_once 'footer.phtml'; endif; ?>
