<?php
include_once "../config.php";

if (!isset($_SESSION['username'])) :?>
    <html><head><meta http-equiv="refresh" content="0; url=/"></head><body></body></html>
<?php else :

$conn = new mysqli($sqlserver,$sqluser,$sqlpass,$sqldb);

$page_name = $_GET['page'];

$sql = "SELECT * FROM `afroraydude-site`.`pages` WHERE `name` LIKE '{$page_name}'";

$result = $conn->query($sql) or die($conn->error);



if ($result->num_rows !== 0) : ?>
    <?php
    while($row = $result->fetch_assoc()) {
        $page_name = $row['page-title'];
        $page_content = $row['content'];
        $page_url = $row['name'];

    } ?>
<?php else :
    $page_title = "404 Page Not Found";

endif;
    $page_title = "Edit Page";
include_once "header.phtml";
?>
    <form class="form" action = "<?php echo htmlspecialchars('/updatepage'); ?>" method = "post">
        <div class="form-group ">
            <label class="control-label requiredField" for="name">
                Page Name
                <span class="asteriskField">
        *
       </span>
            </label>
            <input class="form-control" id="name" name="name" type="text" value="<?= $page_name ?>"/>
        </div>
        <div class="form-group ">
            <label class="control-label requiredField" for="url">
                Page URL
                <span class="asteriskField">
        *
       </span>
            </label>
            <input class="form-control" id="url" name="url" type="text" value="<?= $page_url ?>"/>
        </div>
        <div class="form-group ">
            <label class="control-label requiredField" for="content">
                Page Content
                <span class="asteriskField">
        *
       </span>
            </label>
            <textarea class="form-control editor" cols="40" id="content" name="content" rows="10"><?= $page_content ?></textarea>
        </div>
        <div class="form-group">
            <div>
                <button class="btn btn-primary " name="submit" type="submit">
                    Submit
                </button>
            </div>
        </div>
    </form>
    <a href="/<?php echo $page_url ?>">Go to page</a>

<?php include_once 'footer.phtml'; endif; ?>