<?php
include_once "../config.php";

if (!isset($_SESSION['username']) || $_SESSION['role'] == 3) :?>
    <html><head><meta http-equiv="refresh" content="0; url=/"></head><body></body></html>
<?php else :

$conn = new mysqli($sqlserver,$sqluser,$sqlpass,$sqldb);

$post_id = $_GET['post'];

$post_id = mysqli_real_escape_string($conn, $post_id);

$sql = "SELECT * FROM `afroraydude-site`.`blog` WHERE `id` LIKE '{$post_id}'";

$result = $conn->query($sql) or die($conn->error);



if ($result->num_rows !== 0) : ?>
    <?php
    while($row = $result->fetch_assoc()) {
        $post_title = $row['title'];
        $post_content = $row['content'];
    } ?>
<?php else :
    $page_title = "404 Page Not Found";

endif;
    $page_title = "Edit Post";
include_once "header.phtml";
?>
    <?php
    if (empty($messages) == false) :
        $error = $messages['Error'];
        ?>
        <div class="alert alert-danger alert-dismissable"><p><?= $error[0] ?></p></div>
    <?php endif; ?>
    <form class="form" action = '<?php echo htmlspecialchars("/updatepost?post={$_GET['post']}"); ?>' method = "post">
        <div class="form-group ">
            <label class="control-label requiredField" for="name">
                Page Name
                <span class="asteriskField">
        *
       </span>
            </label>
            <input class="form-control" id="name" name="name" type="text" value="<?= $post_title ?>"/>
        </div>
        <div class="form-group ">
            <label class="control-label requiredField" for="content">
                Post Content
                <span class="asteriskField">
        *
       </span>
            </label>
            <textarea class="form-control editor" cols="40" id="content" name="content" rows="10"><?= $post_content ?></textarea>
        </div>
        <div class="form-group">
            <div>
                <button class="btn btn-primary " name="submit" type="submit">
                    Submit
                </button>
            </div>
        </div>
    </form>
    <a href="/blog">Go to Blog</a>

<?php include_once 'footer.phtml'; endif; ?>