<?php
include_once "../config.php";

if (!isset($_SESSION['username'])) :?>
    <html>
    <head>
        <meta http-equiv="refresh" content="0; url=/">
    </head>
    <body></body>
    </html>
<?php else :

    if (isset($_GET['template'])) {
        $template = file_get_contents("../templates/{$_GET['template']}");
        $template = htmlspecialchars($template);
        $page_title = "Edit Template - {$_GET['template']}";
    } else {
        $template = "No data";
        $page_title = "Edit Template";
    }
    include_once "header.phtml";
    ?>
    <div class="col-md-8">
        <form class="form" action="<?php echo htmlspecialchars("/updatetemplate?template={$_GET['template']}"); ?>" method="post">
            <div class="form-group">

            </div>
            <div class="form-group ">
                <label class="control-label requiredField" for="content">
                    Template Content
                    <span class="asteriskField">
                    *
                    </span>
                </label>
                <textarea class="form-control" cols="40" id="content" name="content" rows="25"><?= $template ?></textarea>
            </div>
            <div class="form-group">
                <div>
                    <button class="btn btn-primary " name="submit" type="submit">
                        Submit
                    </button>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-body">
                <h1>Templates</h1>
                <?php
                $templatelist = scandir('../templates');
                foreach ($templatelist as $templateitem):
                    if ($templateitem !== '.' && $templateitem !== '..'): ?>
                        <a href="/dashboard/edittemplate?template=<?= $templateitem ?>"><?= $templateitem ?></a><br>
                    <?php endif; endforeach; ?>
            </div>
        </div>
    </div>

    <?php include_once 'footer.phtml'; endif; ?>