<?php
include_once "../config.php";

if (!isset($_SESSION['username']) || $_SESSION['role'] != 1) :?>
    <html><head><meta http-equiv="refresh" content="0; url=/"></head><body></body></html>
<?php else :
    $page_title = "Edit CSS";
    include_once "themes/{$theme}/header.phtml";
    $css = file_get_contents('../public/css/bootstrap-theme.css')
?>
    <?php
    if (empty($messages) == false) :
        $error = $messages['Error'];
        ?>
        <div class="alert alert-danger alert-dismissable"><p><?= $error[0] ?></p></div>
    <?php endif; ?>
    <form class="form" action = "<?php echo htmlspecialchars('/updatecss'); ?>" method = "post">

        <div class="form-group ">
            <label class="control-label requiredField" for="content">
                CSS Content
                <span class="asteriskField">
        *
       </span>
            </label>
            <textarea class="form-control editor" cols="40" id="content" name="content" rows="25"><?= $css ?></textarea>
        </div>
        <div class="form-group">
            <div>
                <button class="btn btn-primary " name="submit" type="submit">
                    Submit
                </button>
            </div>
        </div>
    </form>

<?php include_once 'themes/{$theme}/footer.phtml'; endif; ?>