</div>
<?php if (isset($lm_notif)) : ?>
    <p style="display: none"><?php echo $lm_notif; ?></p>
<?php else : ?>
    <p style="display: none"><?= "Nice inspection" ?></p>
<?php endif; ?>

<footer class="footer">
    <div class="container">
        <p class="text-muted">&copy <?= date('Y') ?> Afroraydude. All Rights Reserved</p>
    </div>
</footer>

<!-- Latest compiled and minified JavaScript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="../js/bootstrap.min.js"></script>
</body>
</html>
