<?php try { include '../config.php'; } catch (Exception $e) { include '../ex-config.php'; } ?>
<!DOCTYPE html>
<html>
<head>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-38354391-9', 'auto');
        ga('send', 'pageview');

    </script>
    <!-- Mobile optimization -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="../css/bootstrap.css">

    <!-- Our custom theme theme -->
    <link rel="stylesheet" href="../css/bootstrap-theme.css">

    <title>Afroraydude's Site - <?php echo $page_title; ?></title>

    <script src="js/progressbar.min.js"></script>
</head>
<body>
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Afroraydude's Site</a>
        </div>
        <div id="navbar" class="navbar-right navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                <li><a href="/about">About</a></li>
                <li><a href="/blog">Blog</a></li>
                <li><a href="/contact">Contact</a></li>
                <li><a href="/projects">Projects</a></li>
                <?php if (isset($_SESSION['username'])) : ?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?php echo $_SESSION['username']; ?><span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="/dashboard">Dashboard</a></li>
                            <li role="separator" class="divider"></li>
                            <li class="dropdown-header">Creation</li>
                            <li><a href="/dashboard/createpost">Create Blog Post</a></li>
                            <li><a href="/dashboard/createuser">Create User</a></li>
                            <li><a href="/dashboard/createpage">Create Page</a></li>
                            <li role="separator" class="divider"></li>
                            <li class="dropdown-header">Editing</li>
                            <li><a href="/dashboard/editcss">Edit CSS</a></li>
                            <li><a href="/dashboard/edittemplate">Edit Template</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="/logout">Sign Out</a></li>
                        </ul>
                    </li>
                <?php elseif ($showlogin) : ?>
                    <li><a href="/login">Sign In</a></li>
                <? else : ?>

                <?php endif; ?>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<div class="container normpage">
