<?php
$page_title = "Login";
include_once 'header.phtml';
?>

	<form class="form-signin" action = "<?php echo htmlspecialchars('/auth'); ?>" method = "post">
        <?php
        if (empty($messages) == false) :
            $error = $messages['Error'];
        ?>
            <div class="alert alert-danger alert-dismissable"><p><?= $error[0] ?></p></div>
        <?php endif; ?>
        <div class="col-sm-6">
            <h2 class="form-signin-heading">Please sign in</h2>
            <label for="inputEmail" class="sr-only">Username</label>
            <input type="username" id="username" class="form-control" placeholder="Username" name="username" required autofocus>
            <br>
            <label for="inputPassword" class="sr-only">Password</label>
            <input type="password" id="password" class="form-control" placeholder="Password" name="password" required>
            <!--
            <div class="checkbox">
                <label>
                    <input type="checkbox" value="remember-me"> Remember me
                </label>
            </div>
            -->
            <br>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        </div>
        <br>
        <div class="hidden-xs hidden-sm col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h2>Unauthorized access</h2>
                    <p>Do not attempt to access the dashboard unauthorized or try to game this website by doing so. I mean I can't stop you from trying but, like, its frivolous.</p>
                </div>
            </div>
        </div>
    </form>
<?php include_once "footer.phtml"; ?>