<?php
$page_title = "Setup Site";
if (isset($_GET['step'])) : ?>
    <!DOCTYPE html>
    <html>
    <head>
        <!-- Mobile optimization -->
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="../css/bootstrap.css">

        <!-- Our custom theme theme -->
        <link rel="stylesheet" href="../css/bootstrap-theme.css">

        <title>Muttnick - <?php echo $page_title; ?></title>
    </head>
    <body>
    <div class="container">
    <?php
    $step = $_GET['step'];

    if ($step == '1') :
        include_once 'setup-pages/stepone.phtml';
    elseif ($step == '2') :
        include_once 'setup-pages/steptwo.phtml';
    elseif ($step == '3') :
        include_once 'setup-pages/stepthree.phtml';
    endif;
    echo "</div>";
    //include_once 'footer.phtml';
else :
    echo "<html><head><meta http-equiv='refresh' content='0; url=/setup-site?step=1'></head><body></body></html>";
endif;

