<?php
include_once "../config.php";

$page_title = "Upload";
include_once "themes/{$theme}/header.phtml";
if (!isset($_SESSION['username'])) :?>
    <html><head><meta http-equiv="refresh" content="0; url=/"></head><body></body></html>
<?php else :
?>
    <form action="/upload" method="post" enctype="multipart/form-data">
        Select file to upload:
        <br>
        <input type="file" name="fileToUpload" id="fileToUpload">
        <br>
        <input type="submit" class="btn btn-success" value="Upload File" name="submit">
    </form>

<?php include_once 'themes/{$theme}/footer.phtml'; endif; ?>
